services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - SERVER_PORT=80
      - DB_USER=backenduser
      - DB_PASSWORD=superStrongPassword
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=db
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=backenduser
      - POSTGRES_PASSWORD=superStrongPassword
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backenduser -d db"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
